name: ReadmeChecker

on: 
  push:
    branches:
      - main
    
jobs: 
  readmeChecker:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2 
      
      - name: Readme Checker
        run: | 
          ls -ltr
          if [ ! -f /tmp/foo.txt ]; then
            echo "File not found!"
          fi